#!/bin/bash

#user defined wallpaper

Filepath=$1
background=~/Pictures/.background/bgwp


if [[ $Filepath == "" ]]; then

        echo "its blank idiot"
        read -p "Type filepath here (cancel? [n]): " Filepath

        if [[ $Filepath == "n" ]] || [[ $Filepath == "" ]]; then

                echo "cancelled"
                exit
        fi

fi

cp $Filepath $background

2ff <$background | ff-border e 50 | ff-bright rgba 0 0.5 1 | ff-blur 50 15 > $background.ff

cd ~/.local/src/suckless/st/
        sudo rm config.h
        sudo make clean install
cd

feh --bg-max $background

background=$background.ff

echo $background

pidof st | xargs kill -s USR1
